version: '3.8'
services:
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongo:
    image: mongo:latest
    container_name: mongo_container
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python_app_container
    depends_on:
      - redis
      - mongo
      - mysql
    networks:
      - default
    volumes:
      - .:/app

volumes:
  redis_data:
  mongo_data:
  mysql_data:
